-- Locale Breeze Store metadata setup and seed
-- Run this after schema.sql. It creates the reusable dropdown values used by
-- the admin catalog and product editors, then adds the initial values below.

create table if not exists public.metadata_options (
  id bigint generated by default as identity primary key,
  entity_type varchar(20) not null check (entity_type in ('catalog', 'product')),
  field_key varchar(80) not null check (
    field_key in (
      'category',
      'format',
      'fulfillment_type',
      'currency',
      'image_position',
      'tag'
    )
  ),
  value varchar(120) not null check (char_length(trim(value)) > 0),
  display_order integer not null default 0 check (display_order >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (entity_type, field_key, value)
);

create index if not exists metadata_options_lookup_idx
  on public.metadata_options (entity_type, field_key, is_active, display_order, value);

drop trigger if exists set_metadata_options_updated_at on public.metadata_options;
create trigger set_metadata_options_updated_at
before update on public.metadata_options
for each row
execute function public.set_updated_at();

alter table public.metadata_options enable row level security;

drop policy if exists "Authenticated admins can read metadata options" on public.metadata_options;
create policy "Authenticated admins can read metadata options"
on public.metadata_options
for select
to authenticated
using (true);

drop policy if exists "Authenticated admins can insert metadata options" on public.metadata_options;
create policy "Authenticated admins can insert metadata options"
on public.metadata_options
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated admins can update metadata options" on public.metadata_options;
create policy "Authenticated admins can update metadata options"
on public.metadata_options
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated admins can delete metadata options" on public.metadata_options;
create policy "Authenticated admins can delete metadata options"
on public.metadata_options
for delete
to authenticated
using (true);

-- Catalog editing requires authenticated reads and updates in addition to the
-- public active-catalog policy created by schema.sql.
drop policy if exists "Authenticated admins can read catalogs" on public.catalogs;
create policy "Authenticated admins can read catalogs"
on public.catalogs
for select
to authenticated
using (true);

drop policy if exists "Authenticated admins can update catalogs" on public.catalogs;
create policy "Authenticated admins can update catalogs"
on public.catalogs
for update
to authenticated
using (true)
with check (true);

insert into public.metadata_options (
  entity_type,
  field_key,
  value,
  display_order
) values
  ('catalog', 'image_position', 'center', 0),
  ('catalog', 'image_position', '72% 44%', 1),
  ('catalog', 'image_position', '70% 52%', 2),
  ('catalog', 'image_position', '67% 78%', 3),
  ('catalog', 'image_position', '82% 86%', 4),

  ('product', 'category', 'Digital', 1),
  ('product', 'category', 'Print', 2),
  ('product', 'category', 'Office', 3),
  ('product', 'category', 'Print Supply', 4),
  ('product', 'category', 'Stationery', 5),
  ('product', 'category', 'Computer Part', 6),

  ('product', 'format', 'XLSX + PDF', 1),
  ('product', 'format', 'Booklet', 2),
  ('product', 'format', 'Physical', 3),
  ('product', 'format', 'PDF', 4),

  ('product', 'fulfillment_type', 'download', 1),
  ('product', 'fulfillment_type', 'shipping', 2),
  ('product', 'currency', 'USD', 1),

  ('product', 'image_position', 'center', 0),
  ('product', 'image_position', '72% 65%', 1),
  ('product', 'image_position', '78% 58%', 2),
  ('product', 'image_position', '73% 67%', 3),
  ('product', 'image_position', '62% 79%', 4),
  ('product', 'image_position', '80% 63%', 5),
  ('product', 'image_position', '83% 88%', 6),
  ('product', 'image_position', '87% 92%', 7),
  ('product', 'image_position', '63% 55%', 8),

  ('product', 'tag', 'Download', 1),
  ('product', 'tag', 'Printable', 2),
  ('product', 'tag', 'Business', 3),
  ('product', 'tag', 'Reference', 4),
  ('product', 'tag', 'Beginner', 5),
  ('product', 'tag', 'Tech', 6),
  ('product', 'tag', 'Desk', 7),
  ('product', 'tag', 'School', 8),
  ('product', 'tag', 'Office', 9),
  ('product', 'tag', 'Ink', 10),
  ('product', 'tag', 'Print', 11),
  ('product', 'tag', 'Refill', 12),
  ('product', 'tag', 'Writing', 13),
  ('product', 'tag', 'Notes', 14),
  ('product', 'tag', 'Daily use', 15),
  ('product', 'tag', 'USB-C', 16),
  ('product', 'tag', 'Cable', 17),
  ('product', 'tag', 'Adapter', 18),
  ('product', 'tag', 'Keyboard', 19),
  ('product', 'tag', 'Repair', 20),
  ('product', 'tag', 'Parts', 21),
  ('product', 'tag', 'Planner', 22)
on conflict (entity_type, field_key, value) do nothing;
