-- Locale Breeze Store database schema
-- Run this in the Supabase SQL Editor if the tables do not already exist.
-- The app reads with the public anon/publishable key, so RLS policies below
-- allow visitors to read only active catalog and product rows.

create table if not exists public.catalogs (
  id integer generated by default as identity primary key,
  slug varchar(120) not null unique,
  title varchar(160) not null,
  description text not null,
  sample_item_count integer not null default 0 check (sample_item_count >= 0),
  image_alt text not null,
  image_position varchar(40) not null default 'center',
  examples jsonb not null default '[]'::jsonb,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id integer generated by default as identity primary key,
  slug varchar(120) not null unique,
  sku varchar(80) unique,
  name varchar(180) not null,
  category varchar(120) not null,
  description text not null,
  format varchar(80) not null,
  fulfillment_type varchar(80) not null,
  price_amount numeric(10, 2) not null check (price_amount >= 0),
  currency varchar(3) not null default 'USD',
  image_url text not null default '/locale-breeze-general-store-hero.png',
  image_alt text not null,
  image_position varchar(40) default 'center',
  tags jsonb not null default '[]'::jsonb,
  stock_quantity integer check (stock_quantity is null or stock_quantity >= 0),
  is_featured boolean not null default false,
  is_sample boolean not null default true,
  is_active boolean not null default true,
  display_order integer not null default 0,
  catalog_id integer references public.catalogs(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
  add column if not exists image_url text not null default '/locale-breeze-general-store-hero.png';

-- These indexes match the app's most common reads:
-- active rows ordered for catalog pages, and featured rows for the homepage.
create index if not exists catalogs_active_display_idx
  on public.catalogs (is_active, display_order, id);

create index if not exists products_active_display_idx
  on public.products (is_active, display_order, id);

create index if not exists products_featured_display_idx
  on public.products (is_featured, display_order, id)
  where is_active = true;

create index if not exists products_catalog_id_idx
  on public.products (catalog_id);

-- A tiny trigger helper keeps updated_at current whenever dashboard edits happen.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_catalogs_updated_at on public.catalogs;
create trigger set_catalogs_updated_at
before update on public.catalogs
for each row
execute function public.set_updated_at();

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

alter table public.catalogs enable row level security;
alter table public.products enable row level security;

drop policy if exists "Public can read active catalogs" on public.catalogs;
create policy "Public can read active catalogs"
on public.catalogs
for select
to anon
using (is_active = true);

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products
for select
to anon
using (is_active = true);
