-- Sample data matching the previous local products.ts file.
-- Run after schema.sql if you want the Supabase tables to start with the same
-- catalog and product examples the UI was already designed around.

insert into public.catalogs (
  id,
  slug,
  title,
  description,
  sample_item_count,
  image_alt,
  image_position,
  examples,
  display_order,
  is_active
) values
  (
    1,
    'digital-print',
    'Digital and Print',
    'Downloadable calculators, printable guides, templates, study sheets, and bundled print-ready resources.',
    18,
    'Books and notebooks on a bright store counter representing digital and print catalog items',
    '72% 44%',
    '["PDF guides", "Spreadsheets", "Printable planners"]'::jsonb,
    1,
    true
  ),
  (
    2,
    'books-study',
    'Books and Study Tools',
    'Reference books, notebooks, workbooks, calculators, and practical tools for school, office, and home tasks.',
    16,
    'Books, notebooks, and a calculator arranged as study and office tools',
    '70% 52%',
    '["Books", "Calculators", "Notebooks"]'::jsonb,
    2,
    true
  ),
  (
    3,
    'ink-writing',
    'Ink and Writing',
    'Ink refills, printer cartridges, everyday pens, markers, paper, and desk writing supplies.',
    14,
    'Ink bottles, pens, and printer cartridges on a store counter',
    '67% 78%',
    '["Ink", "Pens", "Printer supplies"]'::jsonb,
    3,
    true
  ),
  (
    4,
    'computer-parts',
    'Computer Parts',
    'Common computer add-ons and replacements such as adapters, cables, keyboard parts, fans, and small components.',
    20,
    'Computer cables, adapters, keyboard keys, and a small cooling fan',
    '82% 86%',
    '["Adapters", "Cables", "Keyboard parts"]'::jsonb,
    4,
    true
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  sample_item_count = excluded.sample_item_count,
  image_alt = excluded.image_alt,
  image_position = excluded.image_position,
  examples = excluded.examples,
  display_order = excluded.display_order,
  is_active = excluded.is_active;

insert into public.products (
  id,
  slug,
  sku,
  name,
  category,
  description,
  format,
  fulfillment_type,
  price_amount,
  currency,
  image_url,
  image_alt,
  image_position,
  tags,
  stock_quantity,
  is_featured,
  is_sample,
  is_active,
  display_order,
  catalog_id
) values
  (
    1,
    'budget-calculator-workbook',
    'LBS-DIG-BUDGET-WORKBOOK',
    'Budget Calculator Workbook',
    'Digital',
    'A spreadsheet-style calculator bundle for monthly budgets, simple forecasting, and printable summaries.',
    'XLSX + PDF',
    'download',
    12.00,
    'USD',
    '/product-images/budget-calculator-workbook.png',
    'Calculator and notebooks representing a budget workbook',
    '72% 65%',
    '["Download", "Printable", "Business"]'::jsonb,
    null,
    true,
    true,
    true,
    1,
    1
  ),
  (
    2,
    'computer-basics-field-guide',
    'LBS-PRT-COMPUTER-BASICS',
    'Computer Basics Field Guide',
    'Print',
    'A compact handbook covering everyday ports, cables, adapters, storage, and simple troubleshooting.',
    'Booklet',
    'shipping',
    9.50,
    'USD',
    '/product-images/computer-basics-field-guide.png',
    'Books and computer parts representing a computer basics guide',
    '78% 58%',
    '["Reference", "Beginner", "Tech"]'::jsonb,
    40,
    true,
    true,
    true,
    2,
    2
  ),
  (
    3,
    'everyday-desk-calculator',
    'LBS-OFC-DESK-CALC',
    'Everyday Desk Calculator',
    'Office',
    'A reliable calculator sample for school, home office, invoices, receipts, and quick store math.',
    'Physical',
    'shipping',
    18.00,
    'USD',
    '/product-images/everyday-desk-calculator.png',
    'A black desk calculator beside books and pens',
    '73% 67%',
    '["Desk", "School", "Office"]'::jsonb,
    24,
    false,
    true,
    true,
    3,
    2
  ),
  (
    4,
    'refill-ink-starter-pack',
    'LBS-INK-STARTER-PACK',
    'Refill Ink Starter Pack',
    'Print Supply',
    'Core ink colors for print-heavy work, sample labels, document prep, and everyday refill needs.',
    'Physical',
    'shipping',
    22.00,
    'USD',
    '/product-images/refill-ink-starter-pack.png',
    'Ink bottles and printer cartridges on a store counter',
    '62% 79%',
    '["Ink", "Print", "Refill"]'::jsonb,
    18,
    true,
    true,
    true,
    4,
    3
  ),
  (
    5,
    'precision-pen-set',
    'LBS-STN-PRECISION-PEN',
    'Precision Pen Set',
    'Stationery',
    'Smooth pens for notes, forms, planning, signatures, sketches, and bundled office kits.',
    'Physical',
    'shipping',
    7.25,
    'USD',
    '/product-images/precision-pen-set.png',
    'Pens arranged beside notebooks and office supplies',
    '80% 63%',
    '["Writing", "Notes", "Daily use"]'::jsonb,
    64,
    false,
    true,
    true,
    5,
    3
  ),
  (
    6,
    'usb-c-adapter-kit',
    'LBS-CMP-USBC-ADAPTER',
    'USB-C Adapter Kit',
    'Computer Part',
    'Common adapters for connecting laptops, monitors, drives, chargers, and small accessories.',
    'Physical',
    'shipping',
    16.00,
    'USD',
    '/product-images/usb-c-adapter-kit.png',
    'USB cables, adapters, and computer connectors',
    '83% 88%',
    '["USB-C", "Cable", "Adapter"]'::jsonb,
    31,
    true,
    true,
    true,
    6,
    4
  ),
  (
    7,
    'keyboard-repair-bits',
    'LBS-CMP-KEYBOARD-BITS',
    'Keyboard Repair Bits',
    'Computer Part',
    'Sample kit for replacing common keys, stabilizers, and small keyboard maintenance pieces.',
    'Physical',
    'shipping',
    11.75,
    'USD',
    '/product-images/keyboard-repair-bits.png',
    'Keyboard keys and small computer parts on a desk',
    '87% 92%',
    '["Keyboard", "Repair", "Parts"]'::jsonb,
    28,
    false,
    true,
    true,
    7,
    4
  ),
  (
    8,
    'printable-study-planner',
    'LBS-DIG-STUDY-PLANNER',
    'Printable Study Planner',
    'Digital',
    'A clean weekly planner designed for students, tutors, and anyone organizing repeat study routines.',
    'PDF',
    'download',
    5.00,
    'USD',
    '/product-images/printable-study-planner.png',
    'Notebooks and paper goods representing a printable study planner',
    '63% 55%',
    '["Download", "Planner", "School"]'::jsonb,
    null,
    true,
    true,
    true,
    8,
    1
  )
on conflict (slug) do update set
  sku = excluded.sku,
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  format = excluded.format,
  fulfillment_type = excluded.fulfillment_type,
  price_amount = excluded.price_amount,
  currency = excluded.currency,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  image_position = excluded.image_position,
  tags = excluded.tags,
  stock_quantity = excluded.stock_quantity,
  is_featured = excluded.is_featured,
  is_sample = excluded.is_sample,
  is_active = excluded.is_active,
  display_order = excluded.display_order,
  catalog_id = excluded.catalog_id;

-- Keep future generated IDs higher than the seeded sample IDs.
select setval(pg_get_serial_sequence('public.catalogs', 'id'), 4, true);
select setval(pg_get_serial_sequence('public.products', 'id'), 8, true);
