-- Supabase PostgreSQL seed for Locale Breeze Store catalogs and products.
--
-- Usage:
-- 1. Open your Supabase project.
-- 2. Go to SQL Editor.
-- 3. Paste this whole file and run it.
--
-- The script is safe to rerun. Existing rows are updated by catalog slug
-- and product SKU.

BEGIN;

CREATE TABLE IF NOT EXISTS public.catalogs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug varchar(120) NOT NULL UNIQUE,
    title varchar(120) NOT NULL,
    description text NOT NULL,
    sample_item_count integer NOT NULL DEFAULT 0,
    image_alt text NOT NULL,
    image_position varchar(32) NOT NULL DEFAULT 'center',
    examples jsonb NOT NULL DEFAULT '[]'::jsonb,
    display_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_catalogs_sample_item_count_non_negative
        CHECK (sample_item_count >= 0)
);

CREATE TABLE IF NOT EXISTS public.products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug varchar(140) NOT NULL UNIQUE,
    sku varchar(64) NOT NULL UNIQUE,
    name varchar(160) NOT NULL,
    category varchar(80) NOT NULL,
    description text NOT NULL,
    format varchar(80) NOT NULL,
    fulfillment_type varchar(32) NOT NULL,
    price_amount numeric(10, 2) NOT NULL,
    currency varchar(3) NOT NULL DEFAULT 'USD',
    image_alt text NOT NULL,
    image_position varchar(32) NOT NULL DEFAULT 'center',
    tags jsonb NOT NULL DEFAULT '[]'::jsonb,
    stock_quantity integer,
    is_featured boolean NOT NULL DEFAULT false,
    is_sample boolean NOT NULL DEFAULT true,
    is_active boolean NOT NULL DEFAULT true,
    display_order integer NOT NULL DEFAULT 0,
    catalog_id integer NOT NULL REFERENCES public.catalogs(id) ON DELETE CASCADE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_products_price_non_negative
        CHECK (price_amount >= 0),
    CONSTRAINT ck_products_stock_quantity_non_negative
        CHECK (stock_quantity IS NULL OR stock_quantity >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_catalogs_slug
    ON public.catalogs (slug);

CREATE UNIQUE INDEX IF NOT EXISTS ix_products_slug
    ON public.products (slug);

CREATE UNIQUE INDEX IF NOT EXISTS ix_products_sku
    ON public.products (sku);

CREATE INDEX IF NOT EXISTS ix_catalogs_display_order
    ON public.catalogs (display_order);

CREATE INDEX IF NOT EXISTS ix_products_catalog_id
    ON public.products (catalog_id);

CREATE INDEX IF NOT EXISTS ix_products_display_order
    ON public.products (display_order);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_catalogs_updated_at ON public.catalogs;
CREATE TRIGGER set_catalogs_updated_at
BEFORE UPDATE ON public.catalogs
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_products_updated_at ON public.products;
CREATE TRIGGER set_products_updated_at
BEFORE UPDATE ON public.products
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.catalogs (
    slug,
    title,
    description,
    sample_item_count,
    image_alt,
    image_position,
    examples,
    display_order,
    is_active
)
VALUES
    (
        'digital-print',
        'Digital and Print',
        'Downloadable calculators, printable guides, templates, study sheets, and bundled print-ready resources.',
        18,
        'Books and notebooks on a bright store counter representing digital and print catalog items',
        '72% 44%',
        '["PDF guides", "Spreadsheets", "Printable planners"]'::jsonb,
        1,
        true
    ),
    (
        'books-study',
        'Books and Study Tools',
        'Reference books, notebooks, workbooks, calculators, and practical tools for school, office, and home tasks.',
        16,
        'Books, notebooks, and a calculator arranged as study and office tools',
        '70% 52%',
        '["Books", "Calculators", "Notebooks"]'::jsonb,
        2,
        true
    ),
    (
        'ink-writing',
        'Ink and Writing',
        'Ink refills, printer cartridges, everyday pens, markers, paper, and desk writing supplies.',
        14,
        'Ink bottles, pens, and printer cartridges on a store counter',
        '67% 78%',
        '["Ink", "Pens", "Printer supplies"]'::jsonb,
        3,
        true
    ),
    (
        'computer-parts',
        'Computer Parts',
        'Common computer add-ons and replacements such as adapters, cables, keyboard parts, fans, and small components.',
        20,
        'Computer cables, adapters, keyboard keys, and a small cooling fan',
        '82% 86%',
        '["Adapters", "Cables", "Keyboard parts"]'::jsonb,
        4,
        true
    )
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    sample_item_count = EXCLUDED.sample_item_count,
    image_alt = EXCLUDED.image_alt,
    image_position = EXCLUDED.image_position,
    examples = EXCLUDED.examples,
    display_order = EXCLUDED.display_order,
    is_active = EXCLUDED.is_active;

INSERT INTO public.products (
    slug,
    sku,
    name,
    category,
    description,
    format,
    fulfillment_type,
    price_amount,
    currency,
    image_alt,
    image_position,
    tags,
    stock_quantity,
    is_featured,
    is_sample,
    is_active,
    display_order,
    catalog_id
)
VALUES
    (
        'budget-calculator-workbook',
        'LB-DIG-001',
        'Budget Calculator Workbook',
        'Digital',
        'A spreadsheet-style calculator bundle for monthly budgets, simple forecasting, and printable summaries.',
        'XLSX + PDF',
        'digital',
        12.00,
        'USD',
        'Calculator and notebooks representing a budget workbook',
        '72% 65%',
        '["Download", "Printable", "Business"]'::jsonb,
        NULL,
        true,
        true,
        true,
        1,
        (SELECT id FROM public.catalogs WHERE slug = 'digital-print')
    ),
    (
        'computer-basics-field-guide',
        'LB-PRT-001',
        'Computer Basics Field Guide',
        'Print',
        'A compact handbook covering everyday ports, cables, adapters, storage, and simple troubleshooting.',
        'Booklet',
        'physical',
        9.50,
        'USD',
        'Books and computer parts representing a computer basics guide',
        '78% 58%',
        '["Reference", "Beginner", "Tech"]'::jsonb,
        35,
        true,
        true,
        true,
        2,
        (SELECT id FROM public.catalogs WHERE slug = 'books-study')
    ),
    (
        'everyday-desk-calculator',
        'LB-OFC-001',
        'Everyday Desk Calculator',
        'Office',
        'A reliable calculator sample for school, home office, invoices, receipts, and quick store math.',
        'Physical',
        'physical',
        18.00,
        'USD',
        'A black desk calculator beside books and pens',
        '73% 67%',
        '["Desk", "School", "Office"]'::jsonb,
        24,
        false,
        true,
        true,
        3,
        (SELECT id FROM public.catalogs WHERE slug = 'books-study')
    ),
    (
        'refill-ink-starter-pack',
        'LB-INK-001',
        'Refill Ink Starter Pack',
        'Print Supply',
        'Core ink colors for print-heavy work, sample labels, document prep, and everyday refill needs.',
        'Physical',
        'physical',
        22.00,
        'USD',
        'Ink bottles and printer cartridges on a store counter',
        '62% 79%',
        '["Ink", "Print", "Refill"]'::jsonb,
        18,
        true,
        true,
        true,
        4,
        (SELECT id FROM public.catalogs WHERE slug = 'ink-writing')
    ),
    (
        'precision-pen-set',
        'LB-STA-001',
        'Precision Pen Set',
        'Stationery',
        'Smooth pens for notes, forms, planning, signatures, sketches, and bundled office kits.',
        'Physical',
        'physical',
        7.25,
        'USD',
        'Pens arranged beside notebooks and office supplies',
        '80% 63%',
        '["Writing", "Notes", "Daily use"]'::jsonb,
        60,
        false,
        true,
        true,
        5,
        (SELECT id FROM public.catalogs WHERE slug = 'ink-writing')
    ),
    (
        'usb-c-adapter-kit',
        'LB-CMP-001',
        'USB-C Adapter Kit',
        'Computer Part',
        'Common adapters for connecting laptops, monitors, drives, chargers, and small accessories.',
        'Physical',
        'physical',
        16.00,
        'USD',
        'USB cables, adapters, and computer connectors',
        '83% 88%',
        '["USB-C", "Cable", "Adapter"]'::jsonb,
        42,
        true,
        true,
        true,
        6,
        (SELECT id FROM public.catalogs WHERE slug = 'computer-parts')
    ),
    (
        'keyboard-repair-bits',
        'LB-CMP-002',
        'Keyboard Repair Bits',
        'Computer Part',
        'Sample kit for replacing common keys, stabilizers, and small keyboard maintenance pieces.',
        'Physical',
        'physical',
        11.75,
        'USD',
        'Keyboard keys and small computer parts on a desk',
        '87% 92%',
        '["Keyboard", "Repair", "Parts"]'::jsonb,
        28,
        false,
        true,
        true,
        7,
        (SELECT id FROM public.catalogs WHERE slug = 'computer-parts')
    ),
    (
        'printable-study-planner',
        'LB-DIG-002',
        'Printable Study Planner',
        'Digital',
        'A clean weekly planner designed for students, tutors, and anyone organizing repeat study routines.',
        'PDF',
        'digital',
        5.00,
        'USD',
        'Notebooks and paper goods representing a printable study planner',
        '63% 55%',
        '["Download", "Planner", "School"]'::jsonb,
        NULL,
        true,
        true,
        true,
        8,
        (SELECT id FROM public.catalogs WHERE slug = 'digital-print')
    )
ON CONFLICT (sku) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    format = EXCLUDED.format,
    fulfillment_type = EXCLUDED.fulfillment_type,
    price_amount = EXCLUDED.price_amount,
    currency = EXCLUDED.currency,
    image_alt = EXCLUDED.image_alt,
    image_position = EXCLUDED.image_position,
    tags = EXCLUDED.tags,
    stock_quantity = EXCLUDED.stock_quantity,
    is_featured = EXCLUDED.is_featured,
    is_sample = EXCLUDED.is_sample,
    is_active = EXCLUDED.is_active,
    display_order = EXCLUDED.display_order,
    catalog_id = EXCLUDED.catalog_id;

COMMIT;
