// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/storefront-redesign/Cinematic.tsx": () => import("../components/mockups/storefront-redesign/Cinematic.tsx"),
  "./components/mockups/storefront-redesign/Current.tsx": () => import("../components/mockups/storefront-redesign/Current.tsx"),
  "./components/mockups/storefront-redesign/Fluid.tsx": () => import("../components/mockups/storefront-redesign/Fluid.tsx"),
  "./components/mockups/storefront-redesign/Interactive.tsx": () => import("../components/mockups/storefront-redesign/Interactive.tsx")
};
